apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: eventhub-data
  labels:
    app.kubernetes.io/name: auth-db-secret
    app.kubernetes.io/part-of: eventhub
    app.kubernetes.io/component: database
    eventhub.io/role: data
type: Opaque
stringData:
  POSTGRES_DB: auth_db
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: auth_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: event-db-secret
  namespace: eventhub-data
  labels:
    app.kubernetes.io/name: event-db-secret
    app.kubernetes.io/part-of: eventhub
    app.kubernetes.io/component: database
    eventhub.io/role: data
type: Opaque
stringData:
  POSTGRES_DB: event_db
  POSTGRES_USER: event_user
  POSTGRES_PASSWORD: event_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: eventhub-app
  labels:
    app.kubernetes.io/name: auth-db-secret
    app.kubernetes.io/part-of: eventhub
    app.kubernetes.io/component: application
    eventhub.io/role: app
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: auth_user
  SPRING_DATASOURCE_PASSWORD: auth_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: event-db-secret
  namespace: eventhub-app
  labels:
    app.kubernetes.io/name: event-db-secret
    app.kubernetes.io/part-of: eventhub
    app.kubernetes.io/component: application
    eventhub.io/role: app
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: event_user
  SPRING_DATASOURCE_PASSWORD: event_pass
